## Write a Numpy program to compute the multiplication of two given matrixes

In [9]:
import numpy as np
from numpy import linalg as LA

In [5]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
np.dot(p,q)

array([[1, 2],
       [3, 4]])

## Write a NumPy program to compute the determinant of a given square array

In [7]:
arr = np.array([[1, 0], [1, 2]])
print(np.linalg.det(arr))

2.0


## Write a NumPy program to compute the cross product of two given vectors

In [6]:
np.cross(p, q)

array([ 2, -3])

## Write a NumPy program to compute the condition number of a given matrix

In [10]:
print(LA.cond(arr))

2.6180339887498953


## Write a NumPy program to compute the inverse of a given matrix

In [12]:
m = np.array([[1,2],[3,4]])
np.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])